import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar/Sidebar";
import FollowBar from "@/components/followbar/FollowBar";
import LoginModal from "@/components/modals/LoginModal";
import RegisterModal from "@/components/modals/RegisterModal";
import { Toaster } from "react-hot-toast";
import Provider from "@/components/provider/Provider";
import EditModal from "@/components/modals/EditModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "X",
  description: "Generated by create next app",
  icons: "/x.svg"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider >
          <Toaster />
          <RegisterModal />
          <LoginModal />
          <EditModal />
          <div className="h-screen bg-black">
            <div className="container h-full pl-5 max-w-6xl">
              <div className="grid grid-cols-4 h-full">
                <Sidebar />
                <div className="col-span-3 lg:col-span-2 border-x-[1px] border-neutral-800
                "
                >
                  {children} 
                </div>
                <FollowBar />
              </div>
            </div>
          </div>
        </Provider>
      </body>
    </html>
  );
}
